title: RWDA Test Blog
description: Prof. Cordell's test blog for RWDA.
show_downloads: true

baseurl: "/rwda-blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://ryancordell.org" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Ryan Cordell"
image: /thumbnail-jumbo.png
twitter:
  username: ryancordell
#  site:
facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  app_id: 1798910940422432 # cayman-blog
  #authors: lorepirri
#  admins:
